# Site settings
title: 
email: genus_ovis@aol.com
description: > # this means to ignore newlines until "baseurl:"
  twigs
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lemjeb.com" # the base hostname & protocol for your site
twitter_username: lemjeb
github_username:  lemjeb

# Build settings
markdown: kramdown
permalink: pretty


defaults:
  - scope:
      path: "resources/twigs_panels"
    values:
      twigs_panel: true